config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'index#home'

  get 'question/:id', to: 'questions#show', as: :question_show
  get 'questions', to: 'questions#index', as: :questions_list

  authenticate :user do
    get 'ask_the_question', to: 'questions#new'
    post 'ask_the_question', to: 'questions#create'
    get 'questions/my', to: 'questions#user_questions', as: :my_questions
    get 'answers/my', to: 'answers#user_answers', as: :my_answers
    post 'new_answer', to: 'answers#new', as: :new_answer
    post 'create_answer', to: 'answers#create', as: :create_answer
    post 'new_correction', to: 'corrections#new', as: :new_correction
    post 'create_correction', to: 'corrections#create', as: :create_correction
    post 'new_accept', to: 'corrections#new_accept', as: :new_accept
    post 'create_accept', to: 'corrections#create_accept', as: :create_accept
  end

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  text        :string
#  user_id     :integer
#  question_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Answer < ActiveRecord::Base

	belongs_to :user
	belongs_to :question
	has_many :corrections, dependent: :destroy

	validates :user, presence: true
	validates :question, presence: true
	validates :text, presence: true
end

app/models/correction.rb
# == Schema Information
#
# Table name: corrections
#
#  id         :integer          not null, primary key
#  text       :string
#  accepted   :boolean
#  user_id    :integer
#  answer_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Correction < ActiveRecord::Base

	belongs_to :user
	belongs_to :answer

	validates :user, presence: true
	validates :answer, presence: true
	validates :text, presence: true

	accepts_nested_attributes_for :answer
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  text       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base

	belongs_to :user
	has_many :answers, dependent: :destroy
	has_many :corrections, through: :answers
	
	validates :title, presence: true
	validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base

  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
  has_many :corrections

  validates :email, presence: true, format: { with: EMAIL_FORMAT }
  validates :encrypted_password, presence: true, confirmation: true, length: { minimum: 6 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def user_answers
		@answers = Answer.all.where(user: current_user).paginate(page: params[:page])
	end

	def new
		@answer = Answer.new(params.permit(:question_id))
		respond_to do |format|
			format.js
		end
	end

	def create
		@answer = Answer.new(answer_params)
		@answer.save

		redirect_to question_show_path(id: @answer.question.id) 
	end

	private

		def answer_params
			params.require(:answer).permit(
				:user_id,
				:question_id,
				:text
			)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/corrections_controller.rb
class CorrectionsController < ApplicationController

	def new
		@correction = Correction.new(params.permit(:answer_id))
	end

	def create
		@correction = Correction.new(correction_params)
		@correction.save

		redirect_to question_show_path(id: @correction.answer.question.id)
	end

	def new_accept
		@correction = Correction.find(params[:correction_id])
		@correction.answer.text = Answer.find(params[:answer_id]).text + " " + @correction.text

		respond_to do |format|
			format.js
		end
	end

	def create_accept
		correction = Correction.find(params[:correction][:id])
		correction.accepted = true
		answer = correction.answer
		answer.text = params[:correction][:answer_attributes][:text]
		answer.save
		correction.save

		redirect_to question_show_path(id: correction.answer.question.id)
	end

	private

		def correction_params
			params.require(:correction).permit(
				:user_id,
				:answer_id,
				:text
			)
		end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  	@questions = Question.last(3).reverse
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
		@questions = Question.paginate(page: params[:page])
	end

	def user_questions
		@questions = Question.where(user: current_user).paginate(page: params[:page])
		render 'index'
	end

	def new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params)
		if @question.save
			# toDo: chenge the route after adding show action
			redirect_to question_show_path(@question)
		else
			render action: :new
		end
	end

	def show
		@question = Question.find(params[:id])
		if @question.nil?
			# add the error text
		end
	end

	private

		def question_params
			params.require(:question).permit(
				:user_id,
				:title,
				:text
			)		
		end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corrections_helper.rb
module CorrectionsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    if  flash.empty?
      messages = resource.errors.map {|key,err| content_tag(:li, err, class: "alert") }.join
    elsif !flash.empty?
      messages = flash.map {|key,err| content_tag(:li, err, class: key) }.join
    else 
      return ''
    end

    if !messages.empty?
      html = <<-HTML
        #{messages}
      </div>
      HTML

      html.html_safe
    else
      return ''
    end
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
	def redner_errors(object)
    if  object.errors.any?
      messages = object.errors.map {|key,err| content_tag(:li, err, class: "alert") }.join
    else 
      return ''
    end

    if !messages.empty?
      html = <<-HTML
      <div class="info"> 
        #{messages}
      </div>
      HTML

      html.html_safe
    else
      return ''
    end
	end

end

app/views/answers/new.js.erb
$(".b-get-answer").html("<%= escape_javascript(render partial: 'partials/answer_form', locals: { answer: @answer }) %>"); 

app/views/answers/user_answers.html.slim
.col-md-12
	.page-header
		h3
			= t 'labels.your_answers'
	.row
		- if @answers.any?
			- @answers.each do |answer|
				.col-sm-6.col-md-4
					.thumbnail
						.caption
							h3
								= answer.question.title
								br
								i.small
									= answer.question.created_at.strftime("%d.%m.%Y")
							p
								i.small
									= t 'label.your_answer'
								br
								= answer.text
							p 
								= link_to t('labels.watch'), question_show_path(answer.question), class: "btn btn-primary" 
			.col-md-12.text-center
					= will_paginate @answers
			.col-sm-12.col-md-12.align-right
				= link_to t('labels.ask_the_question'), ask_the_question_path, class: "btn btn-blue"
		- else
			.col-sm-12.col-md-12
				| Вы ещё не дали ни одного ответа, новы можете поискать
				= link_to t('labels.get_your_own_answers'), questions_list_path

app/views/corrections/new.js.erb
$(".correction_link").on("ajax:success", function() {
	$(this).parent().html("<%= escape_javascript(render partial: 'partials/correction_form', locals: { correction: @correction }) %>"); 
});

app/views/corrections/new_accept.js.erb
$(".accept_correction").on("ajax:success", function() {
	$(this).parent().append("<%= escape_javascript(render partial: 'partials/acceptance_form', locals: { correction: @correction }) %>"); 
	$(this).remove();
});

app/views/index/home.html.slim
.col-md-12#wrapper
	.page-header
		h3
			| Добро подаловать в систему "Вопросы"!
		| Здесь Вы можете задавать вопросы, отвечать на них или корректировать чужие ответы.
	= render 'layouts/partials/latest_questions'

app/views/layouts/_header.html.slim
header
	.logo-block.col-md-2
		.logo
			=link_to "Que?tion?", root_path
	.menu.col-md-4
		- if user_signed_in?
			span
				= t('labels.header.greeting', user_name: current_user.email) + " "  
			= link_to t('labels.header.log_out'), destroy_user_session_path, method: :delete
		- else
			= link_to t('labels.header.log_in') , new_user_session_path
			= " #{t('strings.or')} "
			= link_to t('labels.header.sgin_up') , new_user_registration_path  

app/views/layouts/application.html.slim
doctype html
html
  head
    title Questions
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'layouts/partials/header' 
  	= yield
    = debug(params) if Rails.env.development?

app/views/layouts/partials/_header.html.slim
header
	.logo-block.col-md-2
		.logo
			=link_to "Que?tion?", root_path
	.menu.col-md-8
		- if user_signed_in?
			span
				= t('labels.header.greeting', user_name: current_user.email) + " "  
			= link_to t('labels.header.my_questions'), my_questions_path
			= link_to t('labels.header.my_answers'), my_answers_path
			= link_to t('labels.header.log_out'), destroy_user_session_path, method: :delete
		- else
			= link_to t('labels.header.log_in') , new_user_session_path
			= " #{t('strings.or')} "
			= link_to t('labels.header.sgin_up') , new_user_registration_path  

app/views/layouts/partials/_latest_questions.html.slim
.col-md-12
	.page-header
		h3
			= t 'labels.latest_questions'
	.row
		- if !@questions.nil?
			- @questions.each do |question|
				.col-sm-6.col-md-4
					.thumbnail
						.caption
							h3
								= question.user.email
								br
								i.small
									= question.created_at.strftime("%d.%m.%Y")
							p
								= question.title
							p 
								= link_to t('labels.i_have_an_answer'), question_show_path(question), class: "btn btn-primary" 
			.col-sm-12.col-md-12.align-right
				= link_to t('labels.all_questions'), questions_list_path, class: 'btn'
				= link_to t('labels.ask_the_question'), ask_the_question_path, class: "btn btn-blue"
		- else
			.col-sm-12.col-md-12
				| Вопросов пока нет, но вы можете 
				= link_to t('labels.ask_youre_own_question'), ask_the_question_path

app/views/partials/_acceptance_form.html.slim
= form_for correction, url: create_accept_path, html: { method: :post, class: "form-horizontal col-md-12" } do |f|
	= f.hidden_field :id, vlaue: correction.id
	.form-froup
		.col-sm-10
			= f.fields_for :answer do |answer_f|
				= answer_f.text_area :text, placeholder: t('placeholders.youre_correction'), class: "form-control"
	.form-group
		.col-sm-10
			= f.submit t('labels.accept_correction'), class: "btn btn-default"

app/views/partials/_answer_form.html.slim
= form_for answer, url: create_answer_path, html: { method: :post, class: "form-horizontal col-md-6" } do |f|
	= f.hidden_field :question_id, vlaue: answer.question.id
	= f.hidden_field :user_id, value: current_user.id
	.form-froup
		.col-sm-10
			= f.text_area :text, placeholder: t('placeholders.youre_answer'), class: "form-control"
	.form-group
		.col-sm-10
			= f.submit t('labels.get_the_answer'), class: "btn btn-default"

app/views/partials/_correction_form.html.slim
= form_for correction, url: create_correction_path, html: { method: :post, class: "form-horizontal col-md-6" } do |f|
	= f.hidden_field :answer_id, vlaue: correction.answer.id
	= f.hidden_field :user_id, value: current_user.id
	.form-froup
		.col-sm-10
			= f.text_area :text, placeholder: t('placeholders.youre_correction'), class: "form-control"
	.form-group
		.col-sm-10
			= f.submit t('labels.get_the_corrcetion'), class: "btn btn-default"

app/views/questions/_question_form.html.slim
= form_for @question, url: ask_the_question_path, html: { method: :post, class: "centred-form form-horizontal col-md-6" } do |f|

	= f.hidden_field :user_id, value: current_user.id 
	.form-group  
		= redner_errors(@question)
	.form-group
		= f.label :title, t('labels.forms.question_title'), class: "col-sm-2 control-label"
		.col-sm-10
			= f.text_area :title, autofocus: true, class: "form-control", placeholder: "Текст вашего вопроса"	
	.form-group
		= f.label :text, t('labels.forms.question_text'), class: "col-sm-2 control-label"
		.col-sm-10
			= f.text_area :text, autofocus: true, class: "form-control", placeholder: "Дополение к вопросу"
	.form-group
		.col-sm-offset-2.col-sm-10
			= f.submit t 'labels.ask_the_question', class: "btn btn-default"

app/views/questions/index.html.slim
.col-md-12
	.page-header
		h3
			= t 'labels.your_questions'
	.row
		- if @questions.any?
			- @questions.each do |question|
				.col-sm-6.col-md-4
					.thumbnail
						.caption
							h3
								= question.user.email
								br
								i.small
									= question.created_at.strftime("%d.%m.%Y")
							p
								= question.title
							p 
								= link_to t('labels.i_have_an_answer'), question_show_path(question), class: "btn btn-primary" 
			.col-md-12.text-center
					= will_paginate @questions
			.col-sm-12.col-md-12.align-right
				= link_to t('labels.ask_the_question'), ask_the_question_path, class: "btn btn-blue"
		- else
			.col-sm-12.col-md-12
				| Вопросов пока нет, но вы можете 
				= link_to t('labels.ask_youre_own_question'), ask_the_question_path

app/views/questions/new.html.slim
.col-md-12#wrapper
	.page-header
		h3
			= t 'labels.ask_the_question'
		| В этом разделе вы можете задать вопрос, на который могут ответить другие пользователи сервиса Que?stion?
		= render 'question_form'

app/views/questions/show.html.slim
.col-md-12#wrapper
	.page-header
		h3
			= t 'headers.question_from_user', user_name: @question.user.email
			- if (Time.now - @question.created_at) < (60*60*24)
				span.label.label-default.new_one
					= t 'strings.new_one'
		i
			= @question.created_at.strftime("%d.%m.%Y")
	.content-block
		.question-block
			.question
				= @question.title
				br
				i.small
					= @question.text
			.answers
				- @question.answers.each do |answer|
					.answer-item.col-md-12
						i.small
							= "#{answer.user.email} - #{answer.created_at.strftime("%d.%m.%Y")}" 
						br
						= answer.text
						- answer.corrections.each do |correction|
							.correction-item
								i.small
									= "#{correction.user.email} - #{correction.created_at.strftime("%d.%m.%Y")}" 
								br
								= correction.text + " "
								- if !correction.accepted && (current_user == answer.user)
									= link_to t('labels.accept_correction'), new_accept_path(answer_id: answer.id, correction_id: correction.id), remote: true, method: :post, class: "accept_correction"
								- if correction.accepted
									i.small
									 = "#{t('labels.accepted')} - #{answer.updated_at.strftime("%d.%m.%Y")}"
						.b-get-correction
							= link_to t('labels.create_corretcion'), new_correction_path(answer_id: answer.id), remote: true, method: :post, class: "correction_link"
				.b-get-answer
					= link_to t('labels.get_the_answer'), new_answer_path(question_id: @question.id), remote: true, method: :post